In [377]:
import numpy as np
import pandas as pd

df = pd.read_csv('laptop_data.csv')

In [378]:
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [379]:
#removing unnamed column
df.drop(columns=['Unnamed: 0'],inplace=True)

In [380]:
#removing gb from ram and kg from weight and changing there dtype to int32 and float32
df['Ram'] = df['Ram'].str.replace("GB","")
df['Weight'] = df['Weight'].str.replace("kg","")

df['Ram'] = df['Ram'].astype('int32')
df['Weight'] = df['Weight'].astype('float32')

In [381]:
#changing dtype of price to int
df['Price'] = df['Price'].astype('int32')

In [382]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1303 non-null   object
 1   TypeName          1303 non-null   object
 2   Inches            1303 non-null   float64
 3   ScreenResolution  1303 non-null   object
 4   Cpu               1303 non-null   object
 5   Ram               1303 non-null   int32
 6   Memory            1303 non-null   object
 7   Gpu               1303 non-null   object
 8   OpSys             1303 non-null   object
 9   Weight            1303 non-null   float32
 10  Price             1303 non-null   int32
dtypes: float32(1), float64(1), int32(2), object(7)
memory usage: 96.8+ KB

In [383]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095

In [384]:
df['Touchscreen'] = df['ScreenResolution'].apply(lambda x:1 if 'Touchscreen' in x else 0)

In [385]:
new = df['ScreenResolution'].str.split('x',n=1,expand=True)
df['x_res'] = new[0]
df['y_res'] = new[1]

In [386]:
df['x_res'] = df['x_res'].str.extract(r'(\d+)')

In [387]:
df['x_res'] = df['x_res'].astype('int32')
df['y_res'] = df['y_res'].astype('int32')

In [388]:
df['ppi'] = (((df['x_res']**2) + (df['y_res']**2))**0.5/df['Inches'])

In [389]:
df.drop(columns=['Inches','x_res','y_res','ScreenResolution'],inplace=True)

In [390]:
df.head()

,Company,TypeName,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,Touchscreen,ppi
0,Apple,Ultrabook,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378,0,226.983005
1,Apple,Ultrabook,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895,0,127.677940
2,HP,Notebook,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636,0,141.211998
3,Apple,Ultrabook,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195,0,220.534624
4,Apple,Ultrabook,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095,0,226.983005

In [391]:
df['Cpu_brand'] = df['Cpu'].apply(lambda x:''.join(x.split()[:3]))

def fetch(text):
    if text=='InteL Core i3' or text== 'Intel Core i5' or text=='InteL Core i7':
        return text
    else:
        if text.split()[0]=='Intel':
            return 'Other intel'
        else:
            return 'AMD'

df['Cpu_brand'] = df['Cpu_brand'].apply(fetch)

In [392]:
df.head()

,Company,TypeName,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,Touchscreen,ppi,Cpu_brand
0,Apple,Ultrabook,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378,0,226.983005,AMD
1,Apple,Ultrabook,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895,0,127.677940,AMD
2,HP,Notebook,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636,0,141.211998,AMD
3,Apple,Ultrabook,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195,0,220.534624,AMD
4,Apple,Ultrabook,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095,0,226.983005,AMD

In [393]:
df.drop(columns=['Cpu'],inplace=True)

In [394]:
df['Memory'].value_counts()

Memory
256GB SSD                        412
1TB HDD                          223
500GB HDD                        132
512GB SSD                        118
128GB SSD +  1TB HDD              94
128GB SSD                         76
256GB SSD +  1TB HDD              73
32GB Flash Storage                38
2TB HDD                           16
64GB Flash Storage                15
512GB SSD +  1TB HDD              14
1TB SSD                           14
256GB SSD +  2TB HDD              10
1.0TB Hybrid                       9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
180GB SSD                          5
128GB Flash Storage                4
512GB SSD +  2TB HDD               3
16GB SSD                           3
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
512GB SSD +  256GB SSD             1
512GB SSD +  512GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
64GB SSD                           1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [395]:
df['HDD'] = 0
df['SSD'] = 0
df['Flash'] = 0
df['Hybrid'] = 0

In [396]:
import re

def extract_memory(mem):
    hdd = 0
    ssd = 0
    flash = 0
    hybrid = 0

    parts = mem.split(" + ")

    for part in parts:

        size = int(re.findall(r'\d+', part)[0])

        if "TB" in part:
            size *= 1024

        if "SSD" in part:
            ssd = size

        elif "HDD" in part:
            hdd = size

        elif "Flash Storage" in part:
            flash = size

        elif "Hybrid" in part:
            hybrid = size

    return pd.Series([hdd, ssd, flash, hybrid])

In [397]:
df[['HDD','SSD','Flash','Hybrid']] = df['Memory'].apply(extract_memory)

In [398]:
df.drop(columns=['Memory'],inplace=True)

In [399]:
df.head()

,Company,TypeName,Ram,Gpu,OpSys,Weight,Price,Touchscreen,ppi,Cpu_brand,HDD,SSD,Flash,Hybrid
0,Apple,Ultrabook,8,Intel Iris Plus Graphics 640,macOS,1.37,71378,0,226.983005,AMD,0,128,0,0
1,Apple,Ultrabook,8,Intel HD Graphics 6000,macOS,1.34,47895,0,127.677940,AMD,0,0,128,0
2,HP,Notebook,8,Intel HD Graphics 620,No OS,1.86,30636,0,141.211998,AMD,0,256,0,0
3,Apple,Ultrabook,16,AMD Radeon Pro 455,macOS,1.83,135195,0,220.534624,AMD,0,512,0,0
4,Apple,Ultrabook,8,Intel Iris Plus Graphics 650,macOS,1.37,96095,0,226.983005,AMD,0,256,0,0

In [400]:
df.corr(numeric_only=True)['Price']

Ram            0.743007
Weight         0.210370
Price          1.000000
Touchscreen    0.191226
ppi            0.348331
HDD           -0.094082
SSD            0.676026
Flash         -0.040511
Hybrid         0.008011
Name: Price, dtype: float64

In [401]:
df.drop(columns=['Flash','Hybrid'],inplace=True)

In [402]:
df.head()

,Company,TypeName,Ram,Gpu,OpSys,Weight,Price,Touchscreen,ppi,Cpu_brand,HDD,SSD
0,Apple,Ultrabook,8,Intel Iris Plus Graphics 640,macOS,1.37,71378,0,226.983005,AMD,0,128
1,Apple,Ultrabook,8,Intel HD Graphics 6000,macOS,1.34,47895,0,127.677940,AMD,0,0
2,HP,Notebook,8,Intel HD Graphics 620,No OS,1.86,30636,0,141.211998,AMD,0,256
3,Apple,Ultrabook,16,AMD Radeon Pro 455,macOS,1.83,135195,0,220.534624,AMD,0,512
4,Apple,Ultrabook,8,Intel Iris Plus Graphics 650,macOS,1.37,96095,0,226.983005,AMD,0,256

In [403]:
df['GPU_brand'] = df['Gpu'].apply(lambda x:x.split()[0])
df.drop(columns=['Gpu'],inplace=True)

In [404]:
df['GPU_brand'].value_counts()

GPU_brand
Intel     722
Nvidia    400
AMD       180
ARM         1
Name: count, dtype: int64

In [405]:
df=df[df['GPU_brand'] !='ARM']

In [406]:
df.head()

,Company,TypeName,Ram,OpSys,Weight,Price,Touchscreen,ppi,Cpu_brand,HDD,SSD,GPU_brand
0,Apple,Ultrabook,8,macOS,1.37,71378,0,226.983005,AMD,0,128,Intel
1,Apple,Ultrabook,8,macOS,1.34,47895,0,127.677940,AMD,0,0,Intel
2,HP,Notebook,8,No OS,1.86,30636,0,141.211998,AMD,0,256,Intel
3,Apple,Ultrabook,16,macOS,1.83,135195,0,220.534624,AMD,0,512,AMD
4,Apple,Ultrabook,8,macOS,1.37,96095,0,226.983005,AMD,0,256,Intel

In [407]:
df['OpSys'].value_counts()

OpSys
Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         26
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: count, dtype: int64

In [408]:
def opsys(text):
    if text == 'Windows 10' or text == 'Windows 10 S' or text == 'Windows 7':
        return 'Windows'
    elif text == 'macOS' or text == 'Mac OS X':
        return 'MAC'
    else:
        return 'Others'

In [409]:
df['OpSys'] = df['OpSys'].apply(opsys)

In [410]:
df.head()

,Company,TypeName,Ram,OpSys,Weight,Price,Touchscreen,ppi,Cpu_brand,HDD,SSD,GPU_brand
0,Apple,Ultrabook,8,MAC,1.37,71378,0,226.983005,AMD,0,128,Intel
1,Apple,Ultrabook,8,MAC,1.34,47895,0,127.677940,AMD,0,0,Intel
2,HP,Notebook,8,Others,1.86,30636,0,141.211998,AMD,0,256,Intel
3,Apple,Ultrabook,16,MAC,1.83,135195,0,220.534624,AMD,0,512,AMD
4,Apple,Ultrabook,8,MAC,1.37,96095,0,226.983005,AMD,0,256,Intel

In [411]:
df['Price'] = np.log(df['Price'])

In [412]:
from sklearn.model_selection import train_test_split

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import (
    OneHotEncoder,
    StandardScaler,
    PowerTransformer
)

from sklearn.linear_model import (
    LinearRegression,
    SGDRegressor,
    Ridge,
    Lasso,
    ElasticNet
)

# Model Evaluation
from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error
)

In [413]:
X = df.drop(columns=['Price'])
y = df['Price']

In [414]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.10,random_state=2)

In [415]:
column1 = ColumnTransformer(transformers=[
        ('cat',OneHotEncoder(sparse_output=False, drop='first',handle_unknown='ignore'),[0,1,3,7,10]),
        ('num',StandardScaler(),[2,4,5,8,9])
],remainder='passthrough')

In [416]:
pipe = Pipeline([
    ('pipe1',column1),
    ('lr',LinearRegression())
])

In [417]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('pipe1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [0, 1, 3, 7, 10]),
                                                 ('num', StandardScaler(),
                                                  [2, 4, 5, 8, 9])])),
                ('lr', LinearRegression())])

In [418]:
y_pred = pipe.predict(X_test)

In [419]:
y_pred

array([10.5468598 ,  9.87345986, 10.18484505, 10.16632763, 10.87934894,
       11.42461195, 10.40345255, 10.08781329, 11.10673568,  9.80868476,
       10.76569306, 11.04104062, 11.71387465, 10.89453611, 12.02967728,
       10.7034965 , 10.68432074,  9.78273141, 11.41777716, 11.51067322,
       11.64169764, 11.24996988, 10.73301033, 11.3385706 , 10.24783695,
       11.33382463, 11.03616009, 10.24244801, 10.84830962, 10.43575147,
       10.94561338, 10.05473159, 10.4465742 , 10.99667472, 11.04727651,
       10.68768034, 10.94459043, 10.85408622, 11.13091159, 11.46208624,
       11.64659424, 11.14079255, 10.02903256, 10.35293291, 10.28553324,
       10.04377695, 10.91775106, 11.78716814, 11.49098562, 10.74639009,
       11.58524362, 11.54777664,  9.95908274,  9.69678976, 10.53493738,
       10.65123282, 10.20758045, 10.98261377, 10.21340515, 10.74654725,
       10.84700346, 11.03587306,  9.88740788, 10.99505317, 10.62752635,
       10.31511226, 10.06324295, 11.14105791, 10.66209267, 10.17121236,
       10.94846509, 10.66540112, 10.43589436, 10.2241391 , 10.84014776,
       10.98508126, 11.21060809, 12.05870808, 11.2545724 , 10.2906605 ,
       10.41468043, 10.79379805, 10.92759873, 10.34598171, 11.02110487,
       10.57782652, 11.16203425, 11.15473113, 10.40993329, 10.78907155,
       10.49015502, 10.45583554, 10.2585136 , 11.51354621, 10.58470272,
        9.81647798, 10.22299876, 10.64422192, 10.27206191, 11.35778482,
       10.41694748, 11.1282411 ,  9.97922098, 11.64141479, 10.71001558,
       11.1054309 , 11.1432455 , 11.10916723, 10.76433498, 10.34870459,
       10.65461571, 10.66411716, 10.68065045, 11.31318099, 10.44715387,
       10.5468598 ,  9.64033713, 11.56499369, 10.3095223 , 10.47806813,
       10.26607929, 11.35724496, 10.8888398 , 10.568222  , 10.59281447,
       11.21957169, 10.35326597, 10.24533487, 11.7221358 , 11.35154404,
       10.21862508])

In [420]:
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.7783692576189647
0.23120359701768098

In [437]:
pipe = Pipeline([
    ('pipe1',column1),
    ('lr',Lasso(alpha=0.0009))
])

pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)

In [438]:
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.7820012901592475
0.2296997664527442

In [443]:
pipe = Pipeline([
    ('pipe1',column1),
    ('lr',Ridge(alpha=0.0009))
])

pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)

print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.7783731979495309
0.2312020393125851

In [450]:
pipe = Pipeline([
    ('pipe1',column1),
    ('lr',ElasticNet(alpha=0.001,l1_ratio=0.5))
])

pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)

print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.782682544805853
0.22945204084144297

In [451]:
np.exp(0.229)

np.float64(1.257342039009839)